### ISSUE TITLE
Produce valid datakeys for a Table

### ISSUE THREAD

**Issue by coretl** [bluesky/ophyd-async#145]
```[tasklist]
### Tasks
- [ ] Change `SignalBackend.get_datakey(self, source: str) -> DataKey` to `SignalBackend.get_datakeys(self, name: str, source: str) -> Dict[str, DataKey]` and make `Signal.describe` safely merge the dictionaries of all the read signals
- [ ] Change `SignalBackend.get_reading(self) -> Reading` to `SignalBackend.get_readings(self, name: str) -> Dict[str, Reading]` and make `Signal.read` safely merge the dictionaries of all the read signals
- [ ] Change PVA and CA converters to match
- [ ] Make `PvaTableConverter.get_datakeys` emit a dict with an entry per column of the correct type
- [ ] Make `PvaTableConverter.get_readings` emit a dict with an entry per column of the correct type
```

**Comment by coretl** [comment]
First task is done, but the other tasks still need doing, changing the title to match the new scope.

**Comment by DiamondJoseph** [comment]
Aren't parts 2, 3 done too? SignalBackend now has

```python
    @abstractmethod
    async def get_datakey(self, source: str) -> DataKey:
        """Metadata like source, dtype, shape, precision, units"""
```

with implementations for CA, PVA

and Signal has

```python

    @_add_timeout
    async def describe(self) -> Dict[str, DataKey]:
        """Return a single item dict with the descriptor in it"""
        return {self.name: await self._backend.get_datakey(self.source)}
```

**Comment by coretl** [comment]
still typing...

**Comment by coretl** [comment]
Updated the task list to match, but now I'm not sure if this is the best way to do it, thoughts?

**Comment by coretl** [comment]
Closing as we will support this via numpy structured data via #257
