### ISSUE TITLE
Bring PandA layout into ophyd Device

### ISSUE THREAD

**Issue by coretl** [bluesky/ophyd-async#404]
Needs:

```[tasklist]
### Tasks
- [ ] https://github.com/dls-controls/pymalcolm/pull/390
- [ ] https://github.com/PandABlocks/PandABlocks-webcontrol/issues/8
- [ ] https://github.com/PandABlocks/fastcs-PandABlocks/issues/15
```

Then we get it for free as a pvi provided NTTable
